// Hook for monitoring students and automatically triggering interventions
import { useEffect, useState } from 'react';
import { useAuth } from './useAuth';
import {
  getStudents,
  getStudentAttendance,
  getStudentInterventions,
  createIntervention,
} from '@/lib/firebaseServices';
import {
  calculateRiskAssessment,
  shouldTriggerIntervention,
  createInterventionTrigger,
  triggerToIntervention,
} from '@/lib/analytics';
import type { Intervention } from '@/lib/interventions';

export interface UseInterventionMonitoringOptions {
  enabled?: boolean;
  refreshInterval?: number; // milliseconds
  autoTrigger?: boolean; // automatically create interventions
}

export function useInterventionMonitoring(options: UseInterventionMonitoringOptions = {}) {
  const { enabled = true, refreshInterval = 60000, autoTrigger = false } = options;
  const { user } = useAuth();
  const [interventions, setInterventions] = useState<Intervention[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [triggeredCount, setTriggeredCount] = useState(0);

  useEffect(() => {
    if (!enabled || !user) return;

    const checkStudents = async () => {
      setLoading(true);
      setError(null);
      let triggered = 0;

      try {
        // Get all students
        const students = await getStudents();

        for (const student of students) {
          // Get student's attendance
          const attendance = await getStudentAttendance(student.id);
          if (attendance.length === 0) continue;

          // Calculate risk
          const riskAssessment = calculateRiskAssessment(attendance);

          // Check if intervention should be triggered
          if (shouldTriggerIntervention(riskAssessment)) {
            // Check if already has active intervention
            const existingInterventions = await getStudentInterventions(student.id);
            const hasActive = existingInterventions.some(
              (i) =>
                i.status === 'triggered' ||
                i.status === 'acknowledged' ||
                i.status === 'in-progress'
            );

            if (!hasActive) {
              // Create intervention trigger
              const trigger = createInterventionTrigger(
                student.id,
                student.name || student.email,
                riskAssessment
              );

              if (autoTrigger) {
                // Automatically create intervention in database
                const intervention = triggerToIntervention(trigger, '');
                await createIntervention({
                  ...intervention,
                  id: '', // Will be generated by Firebase
                });
                triggered++;
              }
            }
          }
        }

        setTriggeredCount(triggered);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to check students');
        console.error('Error in intervention monitoring:', err);
      } finally {
        setLoading(false);
      }
    };

    checkStudents();

    // Set up interval
    const interval = setInterval(checkStudents, refreshInterval);
    return () => clearInterval(interval);
  }, [enabled, user, refreshInterval, autoTrigger]);

  return { interventions, loading, error, triggeredCount };
}
